version: '3.8'

services:
  client:
    image: ${IMAGE_FRONT}
    ports:
      - ${FRONT_PORT}
    volumes:
      - ./client:/srv/react-docker
    working_dir: /srv/react-docker
    command: 'npm start'
  back:
    image: ${IMAGE_BACK}
    ports:
      - ${BACK_PORT}
    volumes:
      - ./back:/srv/react-docker
    working_dir: /srv/react-docker
    command: 'npm run dev'
